 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.List;
import javax.swing.JInternalFrame;
import modelo.Canton;
import modelo.Pais;
import modelo.Provincia;
import servicio.CantonServiceImpl;
import servicio.PaisServiceImpl;
import servicio.ProvinciaServiceImpl;

/**
 *
 * @author Jose
 */
public class VentanaPrincipal1 extends javax.swing.JFrame {

    private VentanaPaisCrear ventanaPais;
    private VentanaPaisModificar ventanaPaisModificar;
    private VentanaPaisEliminar ventanaPaisEliminar;
    private VentanaPaisListar ventanaPaisListar;

    private VentanaProvinciaCrear ventanaProvincia;
    private VentanaProvinciaModificar ventanaProvinciaModificar;
    private VentanaProvinciaEliminar ventanaProvinciaEliminar;
    private VentanaProvinciaListar ventanaProvinciaListar;

    private VentanaCantonCrear ventanaCanton;
    private VentanaCantonModificar ventanaCantonModificar;
    private VentanaCantonEliminar ventanaCantonEliminar;
    private VentanaCantonListar ventanaCantonListar;
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );

        jMenu2.setText("Pais");

        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem11.setText("Eliminar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem3.setText("Listar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Provincia");

        jMenuItem5.setText("Crear");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Modificar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem12.setText("Eliminar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem7.setText("Listar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Canton");

        jMenuItem8.setText("Crear");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Modificar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem13.setText("Eliminar");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem10.setText("Listar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.ventanaPaisListar = new VentanaPaisListar();

        ventanaPaisListar.setVisible(true);

        ventanaPaisListar.setResizable(true);
        ventanaPaisListar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPaisListar.setClosable(true);
        ventanaPaisListar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPaisListar);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        this.ventanaProvinciaEliminar = new VentanaProvinciaEliminar();

        ventanaProvinciaEliminar.setVisible(true);

        ventanaProvinciaEliminar.setResizable(true);
        ventanaProvinciaEliminar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaProvinciaEliminar.setClosable(true);
        ventanaProvinciaEliminar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaProvinciaEliminar);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.ventanaPais = new VentanaPaisCrear();

        ventanaPais.setVisible(true);

        ventanaPais.setResizable(true);
        ventanaPais.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPais.setClosable(true);
        ventanaPais.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPais);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        this.ventanaPaisModificar = new VentanaPaisModificar();

        ventanaPaisModificar.setVisible(true);

        ventanaPaisModificar.setResizable(true);
        ventanaPaisModificar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPaisModificar.setClosable(true);
        ventanaPaisModificar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPaisModificar);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed

        this.ventanaPaisEliminar = new VentanaPaisEliminar();

        ventanaPaisEliminar.setVisible(true);

        ventanaPaisEliminar.setResizable(true);
        ventanaPaisEliminar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPaisEliminar.setClosable(true);
        ventanaPaisEliminar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPaisEliminar);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.ventanaProvincia = new VentanaProvinciaCrear();

        ventanaProvincia.setVisible(true);

        ventanaProvincia.setResizable(true);
        ventanaProvincia.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaProvincia.setClosable(true);
        ventanaProvincia.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaProvincia);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.ventanaProvinciaModificar = new VentanaProvinciaModificar();

        ventanaProvinciaModificar.setVisible(true);

        ventanaProvinciaModificar.setResizable(true);
        ventanaProvinciaModificar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaProvinciaModificar.setClosable(true);
        ventanaProvinciaModificar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaProvinciaModificar);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.ventanaProvinciaListar = new VentanaProvinciaListar();

        ventanaProvinciaListar.setVisible(true);

        ventanaProvinciaListar.setResizable(true);
        ventanaProvinciaListar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaProvinciaListar.setClosable(true);
        ventanaProvinciaListar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaProvinciaListar);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
  this.ventanaCanton = new VentanaCantonCrear();

        ventanaCanton.setVisible(true);

        ventanaCanton.setResizable(true);
        ventanaCanton.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaCanton.setClosable(true);
        ventanaCanton.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaCanton);




        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
this.ventanaCantonModificar = new VentanaCantonModificar();

        ventanaCantonModificar.setVisible(true);

        ventanaCantonModificar.setResizable(true);
        ventanaCantonModificar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaCantonModificar.setClosable(true);
        ventanaCantonModificar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaCantonModificar);


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
this.ventanaCantonEliminar = new VentanaCantonEliminar();

        ventanaCantonEliminar.setVisible(true);

        ventanaCantonEliminar.setResizable(true);
        ventanaCantonEliminar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaCantonEliminar.setClosable(true);
        ventanaCantonEliminar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaCantonEliminar);


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
  this.ventanaCantonListar = new VentanaCantonListar();

        ventanaCantonListar.setVisible(true);

        ventanaCantonListar.setResizable(true);
        ventanaCantonListar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaCantonListar.setClosable(true);
        ventanaCantonListar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaCantonListar);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal1().setVisible(true);
                var paisServiceImpl=new PaisServiceImpl();
                List<Pais> paisList=paisServiceImpl.recuperarArchivo("C:/Netbeans1/pais.dat");
                paisServiceImpl.setPaisList(paisList);
                
                var provinciaServiceImpl=new ProvinciaServiceImpl();
                List<Provincia> provinciaList=provinciaServiceImpl.recuperarArchivo("C:/Netbeans1/provincia.dat");
                ProvinciaServiceImpl.setProvinciaList(provinciaList);
                
                var cantonServiceImpl=new CantonServiceImpl();
                
                List<Canton> cantonList=cantonServiceImpl.recuperarArchivo("C:/Netbeans1/canton.dat");
                CantonServiceImpl.setCantonList(cantonList);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
