/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PaisControl;
import controlador.ProvinciaControl;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;
import modelo.Pais;

/**
 *
 * @author Jose
 */
public class VentanaProvinciaListar extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaViaje
     */
    private ProvinciaControl provinciaControl = new ProvinciaControl();
    private PaisControl paisControl = new PaisControl();
    private DefaultTableModel tableModel;

    public VentanaProvinciaListar() {
        initComponents();
        //actualizarCombos();
       
    }
    /*private void actualizarCombos(){
        var data = new String [this.provinciaControl.listar().size()];
        for(var i=0;i<this.provinciaControl.listar().size();i++){
            data[i]=this.provinciaControl.listar().get(i).getNombreProvincia();
        }
        this.jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(data));
    }*/

    public void ActualizarTabla() {
        var data = new Object[this.provinciaControl.listar().size()][6];
        for (var i = 0; i < this.provinciaControl.listar().size(); i++) {
            
            data[i][0] = this.provinciaControl.listar().get(i).getCodigoProvincia();
            data[i][1] = this.provinciaControl.listar().get(i).getNombrePais().getNombrePais();
            data[i][2] = this.provinciaControl.listar().get(i).getNombreProvincia();
            data[i][3] = this.provinciaControl.listar().get(i).getNroCanton();
            data[i][4] = this.provinciaControl.listar().get(i).getHabitantes();
            data[i][5] = this.provinciaControl.listar().get(i).gethabitantesRemunerados();
            

        }
        
        var encabezado = new String[6];
        encabezado[0] = "CódigoProvincia";
        encabezado[1] = "Pais";
        encabezado[2] = "NombreProvincia";
        encabezado[3] = "NroCantones";
        encabezado[4] = "Habitantes";
        encabezado[5] = "HabitantesRemunerados";

        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, encabezado));
        //this.jTable1.setModel(this.tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Lista de  Provincia");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("MOSTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.ActualizarTabla();
        //this.actualizarCombos();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
